version: '3.8'

services:
  angular-app:
    image: node:14
    container_name: angular-app
    working_dir: /usr/src/app
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "4200:4200"
    command: sh -c "npm install && npm start -- --host 0.0.0.0 --poll=2000"
    environment:
      - NODE_ENV=development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4200"]
      interval: 30s
      timeout: 10s
      retries: 3
